# Generated by Django 6.0.2 on 2026-02-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureflag',
            name='note',
        ),
        migrations.AlterField(
            model_name='uitext',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('kz', 'Kazakh'), ('en', 'English')], max_length=2),
        ),
        migrations.AlterField(
            model_name='uitext',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='uitext',
            index=models.Index(fields=['key', 'lang'], name='config_uite_key_66bd15_idx'),
        ),
    ]
