# Generated by Django 6.0.2 on 2026-02-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('service', models.CharField(choices=[('consultation', 'Consultation'), ('admission', 'Admission'), ('contest', 'Grant Contest'), ('online', 'Online Admission')], max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('pay_type', models.CharField(blank=True, default='', max_length=20)),
                ('profile', models.CharField(blank=True, default='', max_length=50)),
                ('track', models.CharField(blank=True, default='', max_length=20)),
                ('desk', models.IntegerField(blank=True, null=True)),
                ('fio', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('social_category', models.CharField(blank=True, default='', max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_type', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
